language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

before_script:
    - composer install

script:
    - vendor/bin/phpunit --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
