language: php

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true
    include:
        - php: 7.1
        - php: 7.2
        - php: nightly

before_script:
    - composer self-update
    - composer install
    - mkdir -p build/logs
 
script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
 
after_success:
    - vendor/bin/coveralls --no-interaction
    - php -r "require_once 'vendor/autoload.php'; AESKW\Tests\Performance::run();";
