language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: nightly

before_script:
    - composer install
    - mkdir -p build/logs
 
script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
 
after_success:
    - vendor/bin/coveralls --no-interaction
